server:
  port: 8100
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  application:
    name: kotlin-service

  webflux:
    base-path: /

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  s3:
    endpoint: ${APPLICATION_S3_ENDPOINT:http://localhost:8333}
    access-key: ${APPLICATION_S3_ACCESS_KEY:secret}
    secret-key: ${APPLICATION_S3_SECRET_KEY:password}

    bucket:
      images: images
      videos: videos
    region: us-east-1

  video:
    temp-dir: ${APPLICATION_VIDEO_TEMP_DIR:/home/elmurod/temp_videos}
    # FFmpeg yo'li. Dockerda shunchaki "ffmpeg" (PATH da bor)
    ffmpeg-path: ffmpeg
  token:
    signing:
      key: 490FU768454B4B623265TMI9966A59893443767HBR7924A226452948404D6334
info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"




