server:
  port: 8100
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  application:
    name: kotlin-service

  webflux:
    base-path: /

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  token:
    signing:
      key: 490FU768454B4B623265TMI9966A59893443767HBR7924A226452948404D6334
info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"

