spring:
  data:
    redis:
      host: redis
      port: 6379
      password: secret
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://postgres:5433/postgres
    username: postgres
    password: secret
    properties:
      schema: osontop

  liquibase:
    url: jdbc:postgresql://postgres:5433/postgres
    user: postgres
    password: secret
    change-log: classpath:db.migration/db.changelog-master.yaml
    enabled: true
    liquibase-schema: osontop
    default-schema: osontop

